# Database
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Resend API & Mittente
RESEND_API_KEY=${RESEND_API_KEY}
app.mail.from=Progretiurb <ordiniRistorante@progretiurb.com>

# Server
server.port=${PORT:8080}

# Spring JPA VPS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true